# Generated by Django 3.2.5 on 2021-07-31 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='', max_length=720)),
                ('priority', models.CharField(choices=[('1', 'مهم و فوری'), ('2', 'غیرمهم و فوری'), ('3', 'مهم و غیرفوری'), ('4', 'غیرمهم و غیرقری')], max_length=2)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('U', 'ناتمام'), ('D', 'انجام شد')], default='U', max_length=1)),
                ('category', models.ManyToManyField(related_name='category', related_query_name='cat_tasks', to='todos.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_group'),
        ),
    ]
