# Generated by Django 3.2.5 on 2021-07-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'مهم و فوری'), ('2', 'غیرمهم و فوری'), ('3', 'مهم و غیرفوری'), ('4', 'غیرمهم و غیرفوری')], max_length=2),
        ),
    ]
